### ISSUE TITLE
list of design update

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/theme_builder#3]
Mettre un titre principal
<h1>Générateur de thème tracim</h1>

Bouton "générer le thème" :
- mettre le bouton sur toute la largeur
- ajouter le texte "Générer le thème"
- passer le bouton en "couleur" (soit btn-success soit la couleur que tu avais mise pour le bouton "reset")

Boutons "reset" :
- utiliser l'icone "undo" ou "eraser"
- mettre le bouton en "transparent" (fond blanc)
- mettre un texte "Réinitialiser"
- passer le bouton en btn-link (pour qu'il ne soit pas mis en valeur)
- passer le bouton en dessous du bouton "générer le thème"

Structure du menu latéral

<h2>Design général</h2>
- Couleur principale
- Couleur secondaire

<h2>Explorateur</h2>
 - Couleur Texte
 <h3>Elément sélectionné</h3>
 - Couleur Texte
 - Couleur Fond
 <h3>Element survolé</h3>
 - Couleur Texte
 - Couleur Fond

**Comment by Skylsmoi** [comment]
https://github.com/tracim/theme_builder/commit/e75330a1c4f2b8335dbe57d4badfc5c9d3b095ee

**Comment by tracim** [comment]
Come, faudrait "passer le bouton en couleur" (soit btn-success soit la couleur que tu avais mise pour le bouton "reset") - cf description originale. Il faut que le bouton soit mis en avant (là il ne ressort pas clairement)
