### ISSUE TITLE
Theme builder main colors not taken into account ?

### ISSUE THREAD

**Issue by tracim** [tracim/theme_builder#5]
Bug:
I generated a bootstrap.css file through theme_builder with the following main colors: 

- main color : #633A11
- second color: #CCCCA6

I applied it to algoo.trac.im.

The colors seem to be taken into account, for example as link color. Unfortunately, main and secondary backgrounds are not as expected.

Thanks to investigate this

**Comment by Skylsmoi** [comment]
this was fixed by the merge of integration_v2 into master
